export const LOAD_QUIZES_START = 'LOAD_QUIZES_START';
export const LOAD_QUIZES_SUCCESS = 'LOAD_QUIZES_SUCCESS';
export const LOAD_QUIZES_ERROR = 'LOAD_QUIZES_ERROR';
export const LOAD_QUIZ_SUCCESS = 'LOAD_QUIZ_SUCCESS';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const QUIZ_FINISH = 'QUIZ_FINISH';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const QUIZ_RETRY = 'QUIZ_RETRY';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
