export const LOAD_QUIZES_START = 'LOAD_QUIZES_START';
export const LOAD_QUIZES_SUCCESS = 'LOAD_QUIZES_SUCCESS';
export const LOAD_QUIZES_ERROR = 'LOAD_QUIZES_ERROR';
export const LOAD_QUIZ_SUCCESS = 'LOAD_QUIZ_SUCCESS';

